apiVersion: batch/v1
kind: CronJob
metadata:
  name: asrv2-mongodb-backups-cj
  namespace: asrv2
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
          - name: asrv2-db-backup
            image: registry.digitalocean.com/topcode/asrv2-db-backup:latest 
            imagePullPolicy: Always
          restartPolicy: OnFailure