apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: asrv2-mongodb-cert
  namespace: asrv2
spec:
  secretName: asrv2-mongodb-tls
  dnsNames:
    - "db.asrv2.com"
  issuerRef:
    name: acme
    kind: ClusterIssuer

