apiVersion: v1
kind: PersistentVolume
metadata:
  name: asrv2-mongodb-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: asrv2-mongodb-storageclass
  local:
    path: /mnt/data

