kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: asrv2-mongodb-storageclass
  namespace: asrv2
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

